name: Aura Bot 24/7

on:
  schedule:
    - cron: '*/20 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # <--- Cambiamos de 20 a 24 aquí

      - name: Instalar Dependencias
        run: npm install

      - name: Ejecutar Aura Bot
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # <--- Añadimos esto para silenciar la alerta
          ETH_API_KEY: ${{ secrets.ETH_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PORT: 8081
        run: node index.js
